### ISSUE TITLE
its dead, Jim

### ISSUE THREAD

**Issue by fommil** [Astrac/consierge#21]
seen that I wasn't getting auto responses today and then checked the server, this is what I found.

Looks like an `Actor` is not restarting somewhere.

```
12:23:00.635 ERROR None e.a.MainApp$ - Unhandled error: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73) ~[akka-http-core-experimental_2.11-1.0.jar:na]
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56) ~[akka-stream-experimental_2.11
-1.0.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73)
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105)
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:23:20.430 ERROR None e.a.MainApp$ - Unhandled error: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73) ~[akka-http-core-experimental_2.11-1.0.jar:na]
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73)
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105)
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:24:09.742 ERROR None e.a.MainApp$ - Unhandled error: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73) ~[akka-http-core-experimental_2.11-1.0.jar:na]
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73)
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105)
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:24:40.469 ERROR None e.a.MainApp$ - Unhandled error: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73) ~[akka-http-core-experimental_2.11-1.0.jar:na]
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.7.jar:1.0.0-M1]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5000 milliseconds while still waiting for outstanding data
        at akka.http.scaladsl.model.HttpEntity$$anon$1.onTimer(HttpEntity.scala:73)
        at akka.stream.TimerTransformer.onScheduled(TimerTransformer.scala:105)
        at akka.stream.impl.TimerTransformerProcessorsImpl$$anon$1$$anonfun$subreceive$1.applyOrElse(TimerTransformerProcessorsImpl.scala:56)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by Astrac** [comment]
It looks like a connection problem: the error is triggered because of the fact that receiving the HTTP response body times out. It would be interesting to know why the configured 5 seconds are not enough to receive the response, maybe github rate limits kicked in?

**Comment by fommil** [comment]
networks are fragile
